# Generated by Django 5.0.2 on 2024-07-22 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit_app4.taluk')),
            ],
            options={
                'unique_together': {('name', 'taluk')},
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(max_length=1500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('gps', models.CharField(max_length=255)),
                ('dairy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit_app4.dairy')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit_app4.employee')),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit_app4.taluk')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit_app4.village')),
                ('visit_types', models.ManyToManyField(to='visit_app4.visittype')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('date_taken', models.DateTimeField()),
                ('gps', models.CharField(max_length=255)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='visit_app4.visit')),
            ],
        ),
    ]
