# Generated by Django 5.0.2 on 2024-07-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_app4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairy',
            name='taluk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dairies', to='visit_app4.taluk'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='taluk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='visit_app4.taluk'),
        ),
    ]
