# Generated by Django 5.0.2 on 2024-07-22 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_app4', '0002_dairy_taluk_alter_photo_date_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dairy',
            name='taluk',
        ),
        migrations.AlterField(
            model_name='village',
            name='taluk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit_app4.taluk'),
        ),
    ]
