# Generated by Django 5.0.1 on 2024-07-23 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_app4', '0004_employee_taluks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='taluks',
        ),
        migrations.AddField(
            model_name='employee',
            name='taluk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visit_app4.taluk'),
            preserve_default=False,
        ),
    ]
