# Generated by Django 5.0.1 on 2024-07-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_app4', '0005_remove_employee_taluks_employee_taluk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='taluk',
        ),
        migrations.AddField(
            model_name='employee',
            name='taluks',
            field=models.ManyToManyField(related_name='employees', to='visit_app4.taluk'),
        ),
    ]
