# Generated by Django 5.0.1 on 2024-07-23 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_app4', '0006_remove_employee_taluk_employee_taluks'),
    ]

    operations = [
        migrations.AddField(
            model_name='dairy',
            name='village',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='visit_app4.village'),
            preserve_default=False,
        ),
    ]
