# Generated by Django 5.0.2 on 2024-07-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_app4', '0007_dairy_village'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='village',
            unique_together=set(),
        ),
    ]
