# Generated by Django 5.0.2 on 2024-07-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_app4', '0008_alter_village_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
