# Generated by Django 5.0.2 on 2024-07-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_app4', '0009_alter_visittype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairy',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='dairy',
            unique_together={('name', 'village')},
        ),
    ]
