# Generated by Django 5.0.2 on 2024-07-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_app4', '0012_alter_dairy_created_at_alter_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
