# Generated by Django 5.0.2 on 2024-07-30 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_app4', '0014_alter_village_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dairy',
            name='created_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dairies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dairy',
            name='modified_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='dairies_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employees_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='modified_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employees_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='photos_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='modified_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='photos_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taluk',
            name='created_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='taluks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taluk',
            name='modified_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='taluks_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='village',
            name='created_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='villages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='village',
            name='modified_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='villages_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='visits_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='modified_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='visits_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visittype',
            name='created_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='visit_types_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visittype',
            name='modified_by',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='visit_types_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
